### ISSUE TITLE
Demo Gif is Very Distorted

### ISSUE THREAD

**Issue by zicklag** [riotkit-org/riotkit-harbor#24]
I'm not sure if it works for other people, but for me the demo Gif on the README is extremely distorted:

![image](https://user-images.githubusercontent.com/25393315/90657517-498fd480-e208-11ea-9147-f39c88d4a5f3.png)

If you want, you could try out my [cast2gif](https://github.com/katharostech/cast2gif) renderer for Asciinema recordings. But unfortunately I don't have automated builds yet. :confused:

**Comment by blackandred** [comment]
Oh, nice, thanks. Nice project :+1:  I will be recording more gifs so I will use for sure. This one I will probably just delete because it is too long. Gifs were designed to be short animations - possibly I misused gifs there :wink:

**Comment by blackandred** [comment]
I remember the Electron & Web Browser took about 15 GB ram to render this :roll_eyes: :joy:

**Comment by zicklag** [comment]
> I remember the Electron & Web Browser took about 15 GB ram to render this

Wow, that's ridiculous. Well I'd be glad if cast2gif can be useful. :smiley: I really need to get automated builds, but if you need anything on it feel free to open an issue. I made it because I literally couldn't find maybe more than one super random python project that could actually generate a GIF from an Asciinema recording without electron or a web browser.

> possibly I misused gifs there wink

Maybe, but I don't know. If it works it works. :wink:

**Comment by blackandred** [comment]
If you will put all building instructions they I can do something in free time to help connect travis or github ci.

**Comment by zicklag** [comment]
I actually might get to it first because I want to remove my dependency on `gifski` and I think that I've already got a build script that will work once I get rid of that. Thanks a lot for the offer, though. I'll let you know if I don't get to it. :+1:.

**Comment by blackandred** [comment]
Sure, I will close this issue and in meantime I created an issue in your project for the CI https://github.com/katharostech/cast2gif/issues/7
